### ISSUE TITLE
Nicer apostrophes in text would be nice

### ISSUE THREAD

**Issue by lazyatom** [freerange/site#1]
I.e. a curly one, rather than a straight one

**Comment by floehopper** [comment]
The Rails version of the website no longer uses `rdiscount`, only `kramdown`, for rendering markdown, so this should be even less of a problem.

**Comment by floehopper** [comment]
I've done the following:

* [Convert single curly quote to apostrophe in markdown](https://github.com/freerange/site/commit/b16d29a4e7b5fb896c4742b88ebf011809756e42)
* [Replace apostrophes with single curly quote](https://github.com/freerange/site/commit/06aeceeb0b75e455af9eb58a3d294ef95dfe4a0b)

I can't think of a way to *ensure* that we always use curly single quotes vs apostrophes, but I believe we are currently using them everywhere. The best idea is to convert as much content as possible to use Markdown.

Closing.
