### ISSUE TITLE
The 'by' dynasnip doesn't work correctly when appearing on a line on its own

### ISSUE THREAD

**Issue by chrisroos** [freerange/site#21]
When the 'by' dynasnip is used on a line of its own, it correctly uses the author's initials (e.g. chris-roos becomes CR), but it doesn't link to the author's page and it results in all remaining 'by' links on the page using the same initials.

To replicate this problem, edit the week 239 week links[1], and move the `{by james-adam}` attribution from the end of the first paragraph to its own line, ensuring there's a newline between the paragraph and the by attribution. If you refresh the page in your browser you should see that all the attribution links have changed to 'JA' and that they're text rather than a link.

[1] You could edit any week link post and use any author, but I figured that a concrete example made it easier to explain the steps to replicate the problem.

**Comment by floehopper** [comment]
This doesn't seem to be a problem in the Rails version of the app. I tried reproducing the problem in `week-239-links` with one of the calls to `ApplicationHelper#by` method within ERB tags and I don't see any of the problems mentioned if it is moved onto a separate line. Closing.
