### ISSUE TITLE
ArgumentError: wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by floehopper** [freerange/site#34]
Errbit: https://gofreerange-errbit.herokuapp.com/apps/54e2340aed53ab1ae5000002/problems/575bdb8aca94c6000c000000

As far as I can tell this is happening because `Vanilla::Routing.parse` is interpreting `/javascripts/h.html` as snip name, "javascripts", part name, "h", and format, "html". According to [this test][1], this seems to be the expected behaviour. It so happens that a `javascripts.snip` exists and so Vanilla tries to obtain the content for the "h" part of this snip by calling the `#h` method on it. This method is aliased to `#html_escape` which is requires exactly one argument, but Vanilla calls it with zero arguments and hence the exception.

I'm not sure there's a simple solution to this, but since it's only happened a few times and seems like someone is manually constructing URLs, I don't think it's worth investigating any further. It does make me wonder whether it might be better for Vanilla to use a different/more obscure URL pattern for a snip part e.g. `/snip-name~part-name.format`. /cc @lazyatom 

[1]: https://github.com/lazyatom/vanilla-rb/blob/0ddf18f97738e2e8dfc973a198ffc82b339e011f/test/core/routing_test.rb#L12

**Comment by lazyatom** [comment]
I can't see the actual error, but I'd say perhaps the simplest fix is to have a more graceful handling of when a snip part is missing, returning a 404 maybe?

**Comment by floehopper** [comment]
The full stack trace is shown below:

```
/usr/lib/ruby/2.1.0/erb.rb:932→ html_escape
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:115→ raw_content
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:98→ render_without_including_snips
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:87→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:70→ block in render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:122→ rendering_and_handling_errors
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:69→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:63→ block in include_snips
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:52→ gsub
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:52→ include_snips
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:88→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:70→ block in render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:122→ rendering_and_handling_errors
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:69→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:63→ block in include_snips
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:52→ gsub
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:52→ include_snips
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/renderers/base.rb:88→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:70→ block in render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:122→ rendering_and_handling_errors
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:69→ render
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:140→ render_in_format
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/app.rb:45→ call
/config.ru:13→ call
rack-1.6.4/lib/rack/static.rb:124→ call
rack-1.6.4/lib/rack/static.rb:124→ call
[GEM_ROOT]/bundler/gems/vanilla-rb-786cfccdaafe/lib/vanilla/static.rb:18→ call
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74→ process_request
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141→ accept_and_process_next_request
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109→ main_loop
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455→ block (3 levels) in start_threads
```

**Comment by floehopper** [comment]
In this case, the problem is that the snip "part method" *does* exist, but only by accident and since it's not a real "part method" happens to have the wrong arity. In fact it only exists, because [vanilla includes the `ERB::Util` module at the top-level][1].

[1]: https://github.com/lazyatom/vanilla-rb/blob/1f1c5624d75e5072706953ce28bee8deb5b099ad/lib/vanilla/renderers/erb.rb#L2

**Comment by floehopper** [comment]
@lazyatom has fixed this in vanilla & soup. I've just upgraded these gems and verified that the problem is fixed i.e. the request now returns a 404 vs 500:
    
        $ curl -I http://localhost:9292/javascripts/h.html
        HTTP/1.1 404 Not Found
        Content-Type: text/html
        Content-Length: 0
        Server: WEBrick/1.3.1 (Ruby/2.1.6/2015-04-13)
        Date: Fri, 15 Jul 2016 11:14:50 GMT
        Connection: Keep-Alive
