### ISSUE TITLE
Remove snips which are hidden by redirects

### ISSUE THREAD

**Issue by floehopper** [freerange/site#43]
There are a bunch of [Apache redirects][1] which are hiding snips. We should be able to delete these snips, although since [this commit][2] we will need to convert all internal links to those snips into external links (c.f. [this commit][3]) in order to avoid exceptions occurring.

[1]: https://github.com/freerange/site/blob/bafd7a8616b4d2f3627775af8e300c97fa2113ec/config/apache/gofreerange.com.conf#L81-L87
[2]: https://github.com/freerange/site/commit/d4e6203618abc89ed8e62153babd650ea63e65af
[3]: https://github.com/freerange/site/commit/f4655675939f2ad6102b31eb9546ef8dd4451904

**Comment by chrisroos** [comment]
I wonder whether an alternative is to move the redirect behaviour from Apache to the app? So, for example, a request for /hello-printer will redirect to the correct new location from within Vanilla.

**Comment by floehopper** [comment]
> I wonder whether an alternative is to move the redirect behaviour from Apache to the app? So, for example, a request for /hello-printer will redirect to the correct new location from within Vanilla.

I think this is a bit orthogonal to removing the redundant snips, i.e. you're talking about an alternative way to implement the redirects. I think I'd prefer to remove the snips first and separately think about changing the way the redirects are implemented: #44.

**Comment by floehopper** [comment]
One complication is that while http://gofreerange.com/harmonia redirects to http://exciting.io/harmonia, the `harmonia` snip is included in http://gofreerange.com/projects, so we can't delete that snip after all.

**Comment by floehopper** [comment]
Note that since [this commit][1] these redirects have been implemented in the Rails app rather than in Apache redirects.

## Redirects with no underlying snip

* `/hello-printer` (underlying snip removed in c4f255d8b4f0919ae1371b320d9dbc7a5a21b021)
* `/printer-questions`
* `/printer-kit`
* `/printer`
* `/say-hello-to-heylist` (underlying snip removed in 6a635a6b601d0a098b11469151ff3abde79ae2a8)

## Redirects with underlying snip

* `/harmonia` (included within `projects` snip)
* `/heylist`

I'm not going to remove the `heylist` project snip, because I can imagine wanting to include it or something like it in the `projects` snip.

I'm happy that this issue is now resolved. Closing.

[1]: https://github.com/freerange/site/commit/4096b8967a453124587c8876ba6c091b16ab39b2
