### ISSUE TITLE
Broken link to Code Editor for Education site

### ISSUE THREAD

**Issue by lenikadali** [freerange/site#448]
Was reading the Go Free Range update when I noticed that the link to the Code Editor for Education site isn't in valid Markdown syntax for links. When I copy the link, I get this:

```
https://gofreerange.com/[https://editor.raspberrypi.org/en/education](https://editor.raspberrypi.org/en/education)
```

I guess you intended to have the link be:
```
[https://editor.raspberrypi.org/en/education](https://editor.raspberrypi.org/en/education)
```

P. S: I am aware that you've all got your hands full so apologies if this comes off as noise 🙃

**Comment by chrislo** [comment]
@lenikadali thank you so much for spotting that and reporting it. I've just pushed a fix so it should be fixed on the site as soon as the changes are deployed.
