### ISSUE TITLE
Relative urls should be absolute in the feed

### ISSUE THREAD

**Issue by lazyatom** [freerange/site#6]
Otherwise images appear broken and links don't work! I believe that the atom feed code in vanilla _should_ take care of this, but it wasn't working for week-153.

**Comment by floehopper** [comment]
This was fixed in the Vanilla version of the site in 8e4b5d518ae3a765e9153621d3dd737df9194d06.

It was fixed in the Rails version of the site in 825fa770ebdd29bf970e9007f8f858f3ae797a07.

Closing.
