### ISSUE TITLE
Links at the end of paragraphs don't render correctly

### ISSUE THREAD

**Issue by chrisroos** [freerange/site#7]
See the source of [week 170](https://raw.githubusercontent.com/freerange/site/master/soups/weeknotes/week-170.snip.markdown).  There are a couple of places where I have a link at the end of a paragraph (Railsberry in the first paragraph, for example).  I've had to put a space between the link and the period to get the link to render correctly.  Without the period, the link renders as plain text.

**Comment by floehopper** [comment]
The Rails version of the app doesn't appear to suffer from this problem. See [this commit](https://github.com/freerange/site/commit/410f67f70b26750d060f6b33d88d0d8f71f040a9) for more details. Closing.
