### ISSUE TITLE
Remove protect_from_forgery declaration in ApplicationController

### ISSUE THREAD

**Issue by floehopper** [freerange/site#76]
Since we're not processing any POST requests, I don't think this is relevant.

**Comment by chrisroos** [comment]
@floehopper: Was the presence of `protect_from_forgery` causing us any problem? I have a slight concern that if we do start processing `POST` requests that we won't have any reminder to add it back.

**Comment by floehopper** [comment]
@chrisroos: Good point. I'm going to re-open this issue to remind us to investigate.
